#!/bin/sh

# Terminate on first failure
set -ex

# Delete existing branches
git checkout --detach
git for-each-ref --format '%(refname:short)' refs/heads |
while read -r branch; do
  git branch -D "$branch"
done

# Add and fetch remotes
git remote add from "$1"  2>/dev/null || git remote set-url from "$1"
git remote add to   "$2"  2>/dev/null || git remote set-url to   "$2"
git fetch --multiple --prune from to

# Create locals
git for-each-ref --format '%(refname)' refs/remotes/from |
{
  errors=0

  while read -r pushfrom; do
    [ "$pushfrom" = "HEAD" ] && continue
    name="${pushfrom##refs/remotes/from/}"
    pushto="refs/remotes/to/$name"
    if ( ! git show-ref "$pushto" > /dev/null) || git merge-base --is-ancestor "$pushto" "$pushfrom" > /dev/null; then
      git branch -f "$name" "$pushfrom"
    else
      echo "Failed to fast-forward $pushfrom to $pushto, relevant commits:"
      git show-ref "$name"
      errors=1
    fi
  done

  # Push to remotes
  git push --tags --follow-tags to refs/heads/*:refs/heads/*

  exit $errors
}
